# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = teensy31
ARDUINO_LIBS = Wire
ARDUINO_LIBS += vl6180x-driver

USER_LIB_PATH += ../

# Teensy explicitly requires Arduino 1.0.x as of Nov 2014
ARDUINO_DIR = /home/vaj2pal/Applications/arduino-1.0.6
# teensy3 and teensy31 explicitly require their own Makefile.
include $(ARDMK_DIR)/Teensy.mk
#include $(ARDMK_DIR)/Arduino.mk


